openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/colinchilds/kvt/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /inventory/{id}:
    get:
      tags:
        - developers
      summary: searches inventory
      operationId: InventoryController.get.id
      description: Get an inventory item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItem'
        '400':
          description: bad input parameter
    patch:
      tags:
        - admins
      summary: updates an inventory item
      operationId: InventoryController.patch
      description: Updates an existing item in the system
      x-auth-roles:
        anyOf:
          - ADMIN
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: item updated
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'
        description: Inventory item to add
    delete:
      tags:
        - admins
      summary: deletes an inventory item
      operationId: InventoryController.delete
      description: Removes an item from the system
      x-auth-roles:
        anyOf:
          - ADMIN
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: item removed
        '400':
          description: 'invalid input, object invalid'
  /inventory:
    get:
      tags:
        - developers
      summary: searches inventory
      operationId: InventoryController.get
      description: Search for all inventory items
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItem'
        '400':
          description: bad input parameter
    post:
      tags:
        - admins
      summary: adds an inventory item
      operationId: InventoryController.post
      description: Adds an item to the system
      x-auth-roles:
        anyOf:
          - ADMIN
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/InventoryItem'
                - type: object
                  required:
                    - name
                    - manufacturer
                    - releaseDate
                    - count
        description: Inventory item to add
components:
  schemas:
    InventoryItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: DQS7GZV
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
        count:
          type: integer
          minimum: 0
          maximum: 100
          example: 1
    Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        phone:
          type: string
          example: 408-867-5309
      type: object